# Generated by Django 4.1.4 on 2022-12-28 17:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_billing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing',
            old_name='name',
            new_name='f_name',
        ),
        migrations.AddField(
            model_name='billing',
            name='l_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
